config/routes.rb
Rails.application.routes.draw do
  root :to => "pages#landing"
  get 'r/two_players/:id', to: 'pages#record_two', as: :r2
  get 'r/three_players/:id', to: 'pages#record_three', as: :r3
  get 'r/four_players/:id', to: 'pages#record_four', as: :r4
  resources :players, only:[:index, :new, :create]
  resources :games, only:[:index, :show, :new, :create]
  resources :participations, only:[:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :winner, :class_name => "Player", optional: true
  has_many :participations
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :game
  belongs_to :player
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :games
  has_many :participations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games=Game.all
  end

  def new

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :get_participants, only: [:record_two, :record_three, :record_four]

  def landing
  end

  def record_two
  end

  def record_three
  end

  def record_four
  end

  private

  def get_participants
    @participants=Participation.where(game:params[:id])
  end


end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

  def new
    @participation=Participation.new
    @registeredplayers=Player.all
  end

  def create

    # Create a new game
    Game.create(date:Date.today)

    # Retrieve the latest game created
    latest_game=Game.last

    # Create a participation for each of the selected players
    params["participation"]["player"].each do |warrior|

      Participation.create(
        game:latest_game,
        player:Player.find(warrior.to_i)
      )

    end

    case params["participation"]["player"].size
    when 2
      redirect_to r2_path(latest_game.id)
    when 3
      redirect_to r3_path(latest_game.id)
    when 4
      redirect_to r4_path(latest_game.id)
    end

  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players=Player.all
  end

  def new
    @newplayer=Player.new
  end

  def create
    Player.create(player_params)
	  redirect_to new_participation_path
  end

  private

  def player_params
  	params.require(:player).permit(:forename, :surname)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/games/index.html.erb
<%= link_to "Quit", root_path, class:""  %>


<h2>
  here the list of all past games
</h2>

<%@games.each do |game|%>
  <p>
    <%=game.date%>
    <strong>Winner:</strong>
    <%=game.winner.forename%>
  </p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sqwore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main_container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/landing.html.erb
<%= link_to "History", games_path, class:""  %>

<h1>Sqwore</h1>
<h3>Best way to keep track of Qwirkle games</h3>

<%= link_to "New game", new_participation_path, class:""  %>

app/views/pages/record_four.html.erb
<div class="menu">
  End game
</div>

<div id="topside" class="side">

  <div class="fourside topleftsidecolor">
    <div class="playerbutton bottomturn rotate_plus90">&#x1F354</div>
    <div class="foursidecontent rotate_plus90">
      <p class="position">2nd with -14 points</p>
      <p class="score">18</p>
      <p class="playername">
        <%=@participants[0].player.forename%>
      </p>
    </div>
  </div>

  <div class="fourside toprightsidecolor">
    <div class="foursidecontent rotate_minus90">
      <p class="position">2nd with -14 points</p>
      <p class="score">18</p>
      <p class="playername">
        <%=@participants[1].player.forename%>
      </p>
    </div>
  </div>

</div>

<div id="bottomside" class="side bottomsidecolor">
  <div class="fourside bottomleftsidecolor">
    <div class="foursidecontent rotate_plus90">
      <p class="position">2nd with -14 points</p>
      <p class="score">18</p>
      <p class="playername">
        <%=@participants[2].player.forename%>
      </p>
    </div>
  </div>

  <div class="fourside bottomrightsidecolor">
    <div class="foursidecontent rotate_minus90">
      <p class="position">2nd with -14 points</p>
      <p class="score">18</p>
      <p class="playername">
        <%=@participants[3].player.forename%>
      </p>
    </div>
  </div>
</div>

app/views/pages/record_three.html.erb
<h2>This is the record page of a 3 players game</h2>

<%=@participants.count%> players

app/views/pages/record_two.html.erb
<div class="menu">
  End game
</div>

<div id="topplayer" class="side topsidecolor">
  <div class="playerbutton rotate180 topturn">&#x1F354</div>
  <div class="sidecontent rotate180">
    <p class="position">2nd with -14 points</p>
    <p class="score">18</p>
    <p class="playername">
      <%=@participants[0].player.forename%>
    </p>
  </div>
</div>

<div id="bottomplayer" class="side bottomsidecolor">
  <div class="playerbutton bottomturn">&#x1F354</div>
  <div class="sidecontent">
    <p class="position">1st with +14 points</p>
    <p class="score">32</p>
    <p class="playername">
      <%=@participants[1].player.forename%>
    </p>
  </div>
</div>

app/views/participations/new.html.erb
<%= link_to "Quit", root_path, class:""  %>

<h1>participations new</h1>

<h2>Who want to have fun?</h2>

<h3>Select in the order of play</h3>

<%=form_for @participation do |p|%>

  <%@registeredplayers.each do |player|%>

    <%= p.check_box :player, {multiple: true}, player.id, false%>
    <%= p.label :player, player.forename%>

  <%end%>

  <br><br>
  <%= link_to "Create new player", new_player_path, class:""  %>

  <br><br>

  <%= p.submit "Let's play!", class: "" %>

<%end%>

app/views/players/index.html.erb
All players listing:

<%@players.each do |player|%>
  <p>
    <%=player.forename%>
    <%=player.surname%>
  </p>
<%end%>

app/views/players/new.html.erb
<%= link_to "Quit", root_path, class:""  %>

<h1>Player new</h1>

<h2>Creation of a new player</h2>

<%=form_for @newplayer do |n|%>

  <%= n.label :forename, "Enter a forename"%>
  <%= n.text_field :forename%>

  <br>

  <%= n.label :surname, "Enter a surname"%>
  <%= n.text_field :surname%>

  <br><br>

  <%= n.submit 'Create new player', class: "" %>

<%end%>